steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/evb-cloudrun-scratch/frontend:$COMMIT_SHA', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/evb-cloudrun-scratch/frontend:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'frontend'
   - '--image'
   - 'gcr.io/evb-cloudrun-scratch/frontend:$COMMIT_SHA'
   - '--region'
   - 'us-central1-a'
   - '--port'
   - '80'
 images:
 - 'gcr.io/evb-cloudrun-scratch/frontend:$COMMIT_SHA'